/*
 * This source file was generated by the Gradle 'init' task
 */
package io.unipac.dsl



fun main() {
    // Access repositories
    val repos = config.getRepositories()
    println("Configured repositories:")
    repos.forEach { repo ->
        println("  - ${repo.name} (${repo.group})")
        println("    Mirrors: ${repo.mirrors.size}")
    }

    println()

    // Access universes
    val universes = config.getUniverses()
    println("Configured universes:")
    universes.forEach { universe ->
        println("  - ${universe.name}: ${universe.description}")
        println("    Packages: ${universe.packages.size}")
        println("    Repos: ${universe.repositories.size}")
        println("    Env vars: ${universe.environmentVariables.size}")
    }
}
